//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aletto_Doyal_A9_A10.AFServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AFServices.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        Aletto_Doyal_A9_A10.AFServices.CompositeType GetDataUsingDataContract(Aletto_Doyal_A9_A10.AFServices.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Aletto_Doyal_A9_A10.AFServices.CompositeType> GetDataUsingDataContractAsync(Aletto_Doyal_A9_A10.AFServices.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAFStations", ReplyAction="http://tempuri.org/IService/GetAFStationsResponse")]
        string GetAFStations(string Zip, string FuelTypes, int Radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAFStations", ReplyAction="http://tempuri.org/IService/GetAFStationsResponse")]
        System.Threading.Tasks.Task<string> GetAFStationsAsync(string Zip, string FuelTypes, int Radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGasStations", ReplyAction="http://tempuri.org/IService/GetGasStationsResponse")]
        string GetGasStations(string Zip, int Radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGasStations", ReplyAction="http://tempuri.org/IService/GetGasStationsResponse")]
        System.Threading.Tasks.Task<string> GetGasStationsAsync(string Zip, int Radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllStations", ReplyAction="http://tempuri.org/IService/GetAllStationsResponse")]
        string GetAllStations(string Zip, string FuelTypes, int Radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllStations", ReplyAction="http://tempuri.org/IService/GetAllStationsResponse")]
        System.Threading.Tasks.Task<string> GetAllStationsAsync(string Zip, string FuelTypes, int Radius);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Aletto_Doyal_A9_A10.AFServices.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Aletto_Doyal_A9_A10.AFServices.IService>, Aletto_Doyal_A9_A10.AFServices.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Aletto_Doyal_A9_A10.AFServices.CompositeType GetDataUsingDataContract(Aletto_Doyal_A9_A10.AFServices.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Aletto_Doyal_A9_A10.AFServices.CompositeType> GetDataUsingDataContractAsync(Aletto_Doyal_A9_A10.AFServices.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string GetAFStations(string Zip, string FuelTypes, int Radius) {
            return base.Channel.GetAFStations(Zip, FuelTypes, Radius);
        }
        
        public System.Threading.Tasks.Task<string> GetAFStationsAsync(string Zip, string FuelTypes, int Radius) {
            return base.Channel.GetAFStationsAsync(Zip, FuelTypes, Radius);
        }
        
        public string GetGasStations(string Zip, int Radius) {
            return base.Channel.GetGasStations(Zip, Radius);
        }
        
        public System.Threading.Tasks.Task<string> GetGasStationsAsync(string Zip, int Radius) {
            return base.Channel.GetGasStationsAsync(Zip, Radius);
        }
        
        public string GetAllStations(string Zip, string FuelTypes, int Radius) {
            return base.Channel.GetAllStations(Zip, FuelTypes, Radius);
        }
        
        public System.Threading.Tasks.Task<string> GetAllStationsAsync(string Zip, string FuelTypes, int Radius) {
            return base.Channel.GetAllStationsAsync(Zip, FuelTypes, Radius);
        }
    }
}
